# Generated by Django 4.2.2 on 2023-08-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0003_alter_wellnessdaily_heart_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellnessdaily',
            name='athlete',
        ),
        migrations.AddField(
            model_name='wellnessdaily',
            name='athlete_id',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
