# Generated by Django 4.2.4 on 2023-10-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_alter_athlete_main_coach'),
        ('physiotherapy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_injury', to='athletes.athlete'),
        ),
    ]
