# Generated by Django 4.2.2 on 2023-07-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_athlete_profile_staff_alter_athlete_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='second_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_second_coach', to='users.staff'),
        ),
    ]
