# Generated by Django 4.2.2 on 2023-07-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_profile_user'),
    ]

    operations = [
    ]
