# Generated by Django 4.2.2 on 2023-07-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20230703_1533'),
    ]

    operations = [
    ]
