# Generated by Django 4.2.2 on 2023-07-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_athlete_profile_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='coach_name',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='nutritionist',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='physiotherapist',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='psychologist',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='second_coach',
        ),
    ]
