# Generated by Django 4.2.2 on 2023-07-03 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_athlete_agent_remove_athlete_coach_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='users.staff'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='coach_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_name', to='users.staff'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='users.staff'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='nutritionist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist', to='users.staff'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='physiotherapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physiotherapist', to='users.staff'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to='users.profile'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='psychologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psychologist', to='users.staff'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='second_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_second_coach', to='users.staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='users.profile'),
        ),
    ]
