# Generated by Django 4.2.2 on 2023-07-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_rename_coach_name_athlete_main_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='athletics_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_athletics_event', to='users.athleticsevent'),
        ),
    ]
