# Generated by Django 4.2.2 on 2023-07-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_athleteevent_results'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AthleticsEvent',
            new_name='Events',
        ),
    ]
