# Generated by Django 4.2.2 on 2023-08-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_rename_competitionresults_competitionresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='AthleticsEvent',
        ),
        migrations.RemoveField(
            model_name='competitionresult',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='competitionresult',
            name='event',
        ),
        migrations.DeleteModel(
            name='AthleteEvent',
        ),
        migrations.DeleteModel(
            name='CompetitionResult',
        ),
    ]
