# Generated by Django 4.2.2 on 2023-06-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
