# Generated by Django 4.2.2 on 2023-06-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='short_intro',
            new_name='doctor_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='nutritionist_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='physiotherapist_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='psychologist_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
