# Generated by Django 4.2.2 on 2023-06-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_short_intro_profile_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='second_coach_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
