# Generated by Django 4.2.2 on 2023-07-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_birth_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techincalteam',
            name='profile',
        ),
        migrations.AddField(
            model_name='techincalteam',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
