# Generated by Django 4.2.2 on 2023-07-01 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_athleticsevent_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='techincalteam',
            name='team_role',
            field=models.CharField(choices=[('Coach', 'Treinador'), ('Nutritionist', 'Nutricionista'), ('Doctor', 'Médico'), ('Psychologist', 'Psicólogo'), ('Physiotherapist', 'Fisioterapeuta'), ('Sport Agent', 'Agente Desportivo')], default='Coach', max_length=60),
        ),
    ]
