# Generated by Django 4.2.2 on 2023-07-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_athlete_athletics_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.athleticsevent')),
            ],
        ),
    ]
