# Generated by Django 4.2.2 on 2023-07-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_athletecurriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship', models.CharField(blank=True, max_length=200, null=True)),
                ('place_country', models.CharField(blank=True, max_length=200, null=True)),
                ('results', models.CharField(blank=True, max_length=200, null=True)),
                ('run_place', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_championship', models.BooleanField(default=False)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.event')),
            ],
        ),
        migrations.DeleteModel(
            name='AthleteCurriculum',
        ),
    ]
