# Generated by Django 4.2.2 on 2023-08-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_rename_event_athleticsevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Athlete',
        ),
        migrations.DeleteModel(
            name='AthleticsEvent',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
