# Generated by Django 4.2.4 on 2023-10-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_profile_email_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_athlete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
