# Generated by Django 4.2.4 on 2023-09-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_profile_email_profile_username'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='athlete',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('Treinador', 'main_coach'), ('Treinador Adjunto', 'second_coach'), ('Agente Desportivo', 'agent'), ('Psicologo', 'psychologist'), ('Fisioterapeuta', 'physiotherapist'), ('Fisiologista', 'physiologist'), ('Médico', 'doctor'), ('Nutricionista', 'nutritionist')], max_length=30),
        ),
    ]
