# Generated by Django 4.2.4 on 2023-09-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_remove_staff_athlete_staff_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff',
            new_name='profile',
        ),
    ]
