# Generated by Django 4.2.2 on 2023-08-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strengthtraining',
            name='left_in_tank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strengthtraining',
            name='exercise',
            field=models.CharField(choices=[('Full Squat', 'Full Squat'), ('Full Front Squat', 'Full Front Squat'), ('1/2 Squat', '1/2 Squat'), ('1/4 Squat', '1/4 Squat'), ('Squat Jump', 'Squat Jump'), ('Bulgarian Squat', 'Bulgarian Squat'), ('Power Clean', 'Power Clean'), ('Hang Clean', 'Hang Clean'), ('Power Snatch', 'Power Snatch'), ('Hang Snatch', 'Hang Snatch'), ('Dead Lift', 'Dead Lift'), ('Bench Press', 'Bench Press'), ('Hip Trust', 'Hip Trust'), ('Lunges', 'Lunges'), ('Chin Up', 'Chin Up'), ('Pull Up', 'Pull Up'), ('Pull Over', 'Pull Over')], default='Full Squat', max_length=60),
        ),
    ]
