# Generated by Django 4.2.2 on 2023-08-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_rename_height_jump_technique_jumpstraining_high_jump_technique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumpstraining',
            name='high_jump_technique',
            field=models.CharField(choices=[('', ''), ('Tesouras', 'Tesouras'), ('Costas', 'Costas')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='jumpstraining',
            name='multijumps_training',
            field=models.CharField(choices=[('', ''), ('Horizontal Impulsion', 'Horizontal Impulsion'), ('Triple Step', 'Triple Step'), ('Triple Hop', 'Triple Hop'), ('Penta Step', 'Penta Step'), ('Penta Hop', 'Penta Hop'), ('Deca Step', 'Deca Step'), ('Penta 4 steps', 'Penta 4 steps'), ('Penta 6 steps', 'Penta 6 steps')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='jumpstraining',
            name='technical_training',
            field=models.CharField(choices=[('', ''), ('High Jump', 'High Jump'), ('Long Jump', 'Long Jump'), ('Triple Jump', 'Triple Jump'), ('Pole Vault', 'Pole Vault')], default='', max_length=60),
        ),
    ]
