# Generated by Django 4.2.2 on 2023-08-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_alter_jumpstraining_high_jump_technique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumpstraining',
            name='high_jump_technique',
            field=models.CharField(blank=True, choices=[('Tesouras', 'Tesouras'), ('Costas', 'Costas')], default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='jumpstraining',
            name='multijumps_training',
            field=models.CharField(blank=True, choices=[('Horizontal Impulsion', 'Horizontal Impulsion'), ('Triple Step', 'Triple Step'), ('Triple Hop', 'Triple Hop'), ('Penta Step', 'Penta Step'), ('Penta Hop', 'Penta Hop'), ('Deca Step', 'Deca Step'), ('Penta 4 steps', 'Penta 4 steps'), ('Penta 6 steps', 'Penta 6 steps')], default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='jumpstraining',
            name='technical_training',
            field=models.CharField(blank=True, choices=[('High Jump', 'High Jump'), ('Long Jump', 'Long Jump'), ('Triple Jump', 'Triple Jump'), ('Pole Vault', 'Pole Vault')], default=None, max_length=60),
        ),
    ]
