# Generated by Django 4.2.2 on 2023-08-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessdaily',
            name='heart_rate',
            field=models.IntegerField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='wellnessdaily',
            name='weight',
            field=models.FloatField(blank=True, default=75, null=True),
        ),
    ]
