# Generated by Django 4.2.2 on 2023-08-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0004_remove_wellnessdaily_athlete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessdaily',
            name='athlete_id',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
