# Generated by Django 4.2.2 on 2023-08-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_delete_athleticsevent'),
        ('wellness', '0005_alter_wellnessdaily_athlete_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellnessdaily',
            name='athlete_id',
        ),
        migrations.AddField(
            model_name='wellnessdaily',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to='athletes.athlete'),
        ),
    ]
