# Generated by Django 4.2.4 on 2023-09-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0008_rename_registation_date_wellnessdaily_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellnessdaily',
            name='heart_rate',
        ),
    ]
