# Generated by Django 4.2.4 on 2023-10-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0009_remove_wellnessdaily_heart_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessdaily',
            name='hidration',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='wellnessdaily',
            name='nutrition',
            field=models.IntegerField(default=50),
        ),
    ]
