# Generated by Django 4.2.4 on 2023-10-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0011_rename_hidration_wellnessdaily_hydration'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessdaily',
            name='hours_sleep',
            field=models.FloatField(default=0),
        ),
    ]
