# Generated by Django 4.2.4 on 2023-10-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0012_wellnessdaily_hours_sleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessdaily',
            name='nr_hours_training',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='wellnessdaily',
            name='training_intensity',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
