# Generated by Django 4.2.4 on 2023-10-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0014_alter_wellnessdaily_nr_hours_training_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessdaily',
            name='nr_hours_training',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wellnessdaily',
            name='training_intensity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
