# Generated by Django 4.2.4 on 2023-10-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0015_alter_wellnessdaily_nr_hours_training_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessdaily',
            name='hours_sleep',
            field=models.FloatField(default=8),
        ),
        migrations.AlterField(
            model_name='wellnessdaily',
            name='weight',
            field=models.FloatField(default=None),
        ),
    ]
