# Generated by Django 4.2.7 on 2023-12-23 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_alter_athlete_main_coach'),
        ('wellness', '0016_alter_wellnessdaily_hours_sleep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellnessdaily',
            name='nr_hours_training',
        ),
        migrations.RemoveField(
            model_name='wellnessdaily',
            name='training_intensity',
        ),
        migrations.AlterField(
            model_name='wellnessdaily',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_wellness', to='athletes.athlete'),
        ),
        migrations.CreateModel(
            name='LoadControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('registration_date', models.DateField()),
                ('training_hours', models.FloatField(default=2)),
                ('intensity', models.IntegerField(default=5)),
                ('load', models.FloatField(default=None)),
                ('obs', models.TextField(blank=True, default='')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_load', to='athletes.athlete')),
            ],
        ),
    ]
