# Generated by Django 4.2.2 on 2023-08-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_alter_wellnessdaily_heart_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessdaily',
            name='heart_rate',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
