# Generated by Django 4.2.2 on 2023-08-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0006_remove_wellnessdaily_athlete_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessdaily',
            name='fatigue',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='wellnessdaily',
            name='heart_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wellnessdaily',
            name='mood',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='wellnessdaily',
            name='muscle_soreness',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='wellnessdaily',
            name='sleep_quality',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='wellnessdaily',
            name='stress_level',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='wellnessdaily',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
