# Generated by Django 4.2.2 on 2023-08-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0007_alter_wellnessdaily_fatigue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellnessdaily',
            old_name='registation_date',
            new_name='registration_date',
        ),
    ]
