# Generated by Django 4.2.2 on 2023-08-16 17:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0038_remove_staff_profile_delete_athlete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleticsEventGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_group', models.CharField(choices=[('Speed', 'Velocidade'), ('Jumps', 'Saltos'), ('Throws', 'Lançamentos'), ('Long distance, Middle Distance e Racewalking', 'Fundo, Meio Fundo e Marcha'), ('Combined Events', 'Provas Combinadas')], default='Combined Events', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='AthleticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('event_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athleticseventgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('team_name', models.CharField(blank=True, max_length=50, null=True)),
                ('url_world_athletics', models.CharField(blank=True, max_length=1000, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='users.profile')),
                ('athletics_event_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athleticseventgroup')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='users.profile')),
                ('main_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_name', to='users.profile')),
                ('nutritionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist', to='users.profile')),
                ('physiotherapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physiotherapist', to='users.profile')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to='users.profile')),
                ('psychologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psychologist', to='users.profile')),
                ('second_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_second_coach', to='users.profile')),
            ],
        ),
    ]
