# Generated by Django 4.2.2 on 2023-08-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='athletics_event_group',
            new_name='event_group',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='doctor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='main_coach',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='nutritionist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='physiotherapist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='psychologist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='second_coach',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
