# Generated by Django 4.2.2 on 2023-08-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_athlete_url_fpacompeticoes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AthleticsEvent',
        ),
    ]
