# Generated by Django 4.2.4 on 2023-09-22 13:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0006_alter_athlete_main_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('cmj', models.FloatField(blank=True, null=True, verbose_name='Counter Movement Jump (CMJ)')),
                ('drop_jump', models.FloatField(blank=True, null=True, verbose_name='Drop Jump')),
                ('average_rsi', models.FloatField(blank=True, null=True)),
                ('imtp_peak_force', models.FloatField(blank=True, null=True)),
                ('imtp_relative', models.FloatField(blank=True, null=True)),
                ('adductor_left_peak_force', models.FloatField(blank=True, null=True)),
                ('adductor_right_peak_force', models.FloatField(blank=True, null=True)),
                ('relative_add', models.FloatField(blank=True, null=True)),
                ('abductor_left_peak_force', models.FloatField(blank=True, null=True)),
                ('abductor_right_peak_force', models.FloatField(blank=True, null=True)),
                ('relative_abd', models.FloatField(blank=True, null=True)),
                ('abd_left_peak_force', models.FloatField(blank=True, null=True)),
                ('abd_right_peak_force', models.FloatField(blank=True, null=True)),
                ('iso_hams', models.FloatField(blank=True, null=True)),
                ('iso_hams_right', models.FloatField(blank=True, null=True)),
                ('iso_hams_left', models.FloatField(blank=True, null=True)),
                ('iso_quad_left', models.FloatField(blank=True, null=True)),
                ('iso_quad_right', models.FloatField(blank=True, null=True)),
                ('calf_left', models.FloatField(blank=True, null=True)),
                ('calf_right', models.FloatField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile_physiology_evaluation', to='athletes.athlete')),
            ],
        ),
    ]
