# Generated by Django 4.2.7 on 2023-12-25 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_alter_athlete_main_coach'),
        ('nutrition', '0002_rename_head_antropometricdata_perimeter_abdominal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antropometricdata',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_antropometric', to='athletes.athlete'),
        ),
    ]
