# Generated by Django 4.2.7 on 2023-12-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_antropometricdata_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='antropometricdata',
            name='body_muscle',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='antropometricdata',
            name='prega_adbominal',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='antropometricdata',
            name='prega_bicipal',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='antropometricdata',
            name='prega_coxa',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='antropometricdata',
            name='prega_gemeo',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='antropometricdata',
            name='prega_ilio_cristal',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='antropometricdata',
            name='prega_subescapular',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='antropometricdata',
            name='prega_supra_espinal',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='antropometricdata',
            name='prega_tricipal',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='body_fat',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='perimeter_abdominal',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='perimeter_calf',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='perimeter_hip',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='perimeter_relax_arm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='perimeter_strenght_arm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='perimeter_thigh',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
    ]
