# Generated by Django 4.2.7 on 2023-12-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_antropometricdata_body_muscle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antropometricdata',
            name='body_muscle',
        ),
        migrations.RemoveField(
            model_name='antropometricdata',
            name='prega_adbominal',
        ),
        migrations.RemoveField(
            model_name='antropometricdata',
            name='prega_bicipal',
        ),
        migrations.RemoveField(
            model_name='antropometricdata',
            name='prega_coxa',
        ),
        migrations.RemoveField(
            model_name='antropometricdata',
            name='prega_gemeo',
        ),
        migrations.RemoveField(
            model_name='antropometricdata',
            name='prega_ilio_cristal',
        ),
        migrations.RemoveField(
            model_name='antropometricdata',
            name='prega_subescapular',
        ),
        migrations.RemoveField(
            model_name='antropometricdata',
            name='prega_supra_espinal',
        ),
        migrations.RemoveField(
            model_name='antropometricdata',
            name='prega_tricipal',
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='body_fat',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='perimeter_abdominal',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='perimeter_calf',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='perimeter_hip',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='perimeter_relax_arm',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='perimeter_strenght_arm',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='perimeter_thigh',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
