# Generated by Django 4.2.7 on 2024-01-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_antropometricdata_body_muscle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antropometricdata',
            old_name='prega_adbominal',
            new_name='prega_abdominal',
        ),
        migrations.AlterField(
            model_name='antropometricdata',
            name='obs',
            field=models.TextField(null=True),
        ),
    ]
