# Generated by Django 4.2.7 on 2024-02-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_rename_prega_adbominal_antropometricdata_prega_abdominal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antropometricdata',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
