# Generated by Django 4.2.2 on 2023-06-24 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profiles/profile_default.png', null=True, upload_to='profiles/')),
                ('birth_date', models.DateField(max_length=8)),
                ('event_profile', models.CharField(choices=[('sprinter', 'Velocidade'), ('jumper', 'Saltos'), ('thrower', 'Lançamentos'), ('runner', 'Fundo, Meio Fundo e Marcha'), ('combined_events', 'Provas Combinadas')], max_length=20)),
                ('agent', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=10)),
                ('birth_place', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
