# Generated by Django 4.2.2 on 2023-06-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='event_profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='coach_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='event_group',
            field=models.CharField(choices=[('Velocidade', 'Velocidade'), ('Saltos', 'Saltos'), ('Lançamentos', 'Lançamentos'), ('Fundo, Meio Fundo e Marcha', 'Fundo, Meio Fundo e Marcha'), ('Provas Combinadas', 'Provas Combinadas')], default='Provas Combinadas', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_intro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='team_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
