# Generated by Django 4.2.2 on 2023-06-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_event_profile_profile_coach_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='agent',
            new_name='agent_name',
        ),
    ]
