# Generated by Django 4.2.2 on 2023-06-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
