# Generated by Django 4.2.2 on 2023-07-01 07:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_user_type_alter_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_group', models.CharField(choices=[('100m', '100m'), ('200m', '200m'), ('400m', '400m'), ('800m', '800m'), ('1500m', '1500m'), ('3000m', '3000m'), ('5000m', '5000m'), ('10000m', '10000m'), ('Half Marathon', 'Half Marathon'), ('Marathon', 'Marathon'), ('100m Hurdles', '100m Hurdles'), ('110m Hurdles', '110m Hurdles'), ('400m Hurdles', '400m Hurdles'), ('2000m Steeplechase', '2000m Steeplechase'), ('3000m Steeplechase', '3000m Steeplechase'), ('4x100m Relay', '4x100m Relay'), ('4x400m Relay', '4x400m Relay'), ('High Jump', 'High Jump'), ('Long Jump', 'Long Jump'), ('Triple Jump', 'Triple Jump'), ('Pole Vault', 'Pole Vault'), ('Shot Put', 'Shot Put'), ('Discus Throw', 'Discus Throw'), ('Hammer Throw', 'Hammer Throw'), ('Javelin Throw', 'Javelin Throw'), ('Decathlon', 'Decathlon'), ('Heptathlon', 'Heptathlon'), ('60m', '60m'), ('60m Hurdles', '60m Hurdles'), ('300m', '300m'), ('300m Hurdles', '300m Hurdles'), ('1000m', '1000m'), ('Octathlon', 'Octathlon'), ('Triathlon', 'Triathlon')], default='Provas Combinadas', max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coach_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='event_group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nutritionist_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='physiotherapist_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='psychologist_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='second_coach_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10),
        ),
        migrations.CreateModel(
            name='TechincalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_role', models.CharField(choices=[('Coach', 'Treinador'), ('SecondCoach', 'Treinador Adjunto'), ('Nutritionist', 'Nutricionista'), ('Doctor', 'Médico'), ('Psychologist', 'Psicólogo'), ('Physiotherapist', 'Fisioterapeuta')], default='Coach', max_length=60)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=50, null=True)),
                ('event_group', models.CharField(choices=[('Speed', 'Velocidade'), ('Jumps', 'Saltos'), ('Throws', 'Lançamentos'), ('Long distance, Middle Distance e Racewalking', 'Fundo, Meio Fundo e Marcha'), ('Combined Events', 'Provas Combinadas')], default='Combined Events', max_length=60)),
                ('agent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='users.techincalteam')),
                ('coach_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_name', to='users.techincalteam')),
                ('doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='users.techincalteam')),
                ('nutritionist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist', to='users.techincalteam')),
                ('physiotherapist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physiotherapist', to='users.techincalteam')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('psychologist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psychologist', to='users.techincalteam')),
                ('second_coach', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_coach', to='users.techincalteam')),
            ],
        ),
    ]
