# Generated by Django 4.2.2 on 2023-07-01 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_athleticsevent_remove_profile_agent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techincalteam',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
