# Generated by Django 4.2.2 on 2023-07-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='coach_name',
            new_name='main_coach',
        ),
        migrations.AddField(
            model_name='athlete',
            name='url_world_athletics',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/profile_default.png', null=True, upload_to='static/profiles/'),
        ),
    ]
