# Generated by Django 4.2.2 on 2023-07-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_rename_athleticsevent_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
