# Generated by Django 4.2.2 on 2023-08-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_remove_staff_profile_delete_athlete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
