# Generated by Django 4.2.2 on 2023-08-16 21:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0041_profile_email_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('staff_type', models.CharField(choices=[('Treinador', 'main_coach'), ('Treinador Adjunto', 'second_coach'), ('Agente Desportivo', 'agent'), ('Psicologo', 'psychologist'), ('Fisioterapeuta', 'physiotherapist'), ('Médico', 'doctor'), ('Nutricionista', 'nutritionist')], max_length=30)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='users.profile')),
            ],
        ),
    ]
