# Generated by Django 4.2.4 on 2023-09-24 10:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0006_alter_athlete_main_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgramme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('warmup', models.TextField(blank=True, null=True)),
                ('main', models.TextField(blank=True, null=True)),
                ('cool_down', models.TextField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile_training_programme', to='athletes.athlete')),
            ],
        ),
    ]
