# Generated by Django 4.2.4 on 2023-09-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_programme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogramme',
            name='hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogramme',
            name='intensity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainingprogramme',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
