# Generated by Django 4.2.4 on 2023-10-21 18:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_alter_athlete_main_coach'),
        ('training_programme', '0002_trainingprogramme_hours_trainingprogramme_intensity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('competition_event', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.CharField(blank=True, max_length=255, null=True)),
                ('season_period', models.CharField(blank=True, max_length=255, null=True)),
                ('competition_result', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile_goal', to='athletes.athlete')),
            ],
        ),
    ]
