# Generated by Django 4.2.4 on 2023-10-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_athleticscurriculum_competition_event'),
        ('training_programme', '0003_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='competition_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile_goal', to='competitions.competitionevent'),
        ),
    ]
