# Generated by Django 4.2.2 on 2023-08-16 21:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0002_rename_athletics_event_group_athlete_event_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('competition_name', models.CharField(blank=True, max_length=200, null=True)),
                ('competition_local', models.CharField(blank=True, max_length=200, null=True)),
                ('competition_date', models.DateField(blank=True, null=True)),
                ('competition_result', models.FloatField(blank=True, null=True)),
                ('competition_wind', models.FloatField(blank=True, null=True)),
                ('competition_period', models.CharField(choices=[('Indoor', 'Pista Coberta'), ('Outdoor', 'Ar Livre')], max_length=10)),
                ('is_final', models.BooleanField(default=False)),
                ('is_heat', models.BooleanField(default=False)),
                ('is_semi_final', models.BooleanField(default=False)),
                ('competition_category', models.CharField(choices=[('OW', 'OW 1'), ('DF', 'DF'), ('GW', 'GW'), ('GL', 'GL'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10)),
                ('world_athletics_points', models.IntegerField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='athletes.athlete')),
            ],
        ),
    ]
