# Generated by Django 4.2.2 on 2023-08-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competition_wind_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='event',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
