# Generated by Django 4.2.2 on 2023-08-18 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_competition_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitionevent'),
        ),
    ]
