# Generated by Django 4.2.4 on 2023-10-21 18:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_alter_athlete_main_coach'),
        ('competitions', '0006_alter_competition_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competition_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_category',
            field=models.CharField(choices=[('OW', 'OW 1'), ('DF', 'DF'), ('GW', 'GW'), ('GL', 'GL'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='wind_direction',
            field=models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], default=' ', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='AthleticsCurriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('competition_date', models.DateField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athletics_curriculum', to='athletes.athlete')),
            ],
        ),
    ]
