# Generated by Django 4.2.4 on 2023-10-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_competition_competition_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition_category',
            field=models.CharField(choices=[('OW', 'OW 1'), ('DF', 'DF'), ('GW', 'GW'), ('GL', 'GL'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='F', max_length=10),
        ),
    ]
