# Generated by Django 4.2.4 on 2023-10-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_competition_competition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionevent',
            name='m_or_points',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competitionevent',
            name='seconds',
            field=models.BooleanField(default=False),
        ),
    ]
