# Generated by Django 4.2.4 on 2023-10-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_competitionevent_m_or_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionevent',
            name='wind_influence',
            field=models.BooleanField(default=False),
        ),
    ]
