# Generated by Django 4.2.4 on 2023-10-22 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_competitionevent_wind_influence'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleticscurriculum',
            name='competition_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_event_curriculum', to='competitions.competitionevent'),
        ),
    ]
