# Generated by Django 4.2.7 on 2024-02-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_athleticscurriculum_competition_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionevent',
            old_name='m_or_points',
            new_name='short_track',
        ),
        migrations.RenameField(
            model_name='competitionevent',
            old_name='seconds',
            new_name='timing',
        ),
    ]
