# Generated by Django 4.2.7 on 2024-02-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_competition_competition_result_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='wind_direction',
            field=models.CharField(choices=[('+', 'Positive'), ('', 'Inddor'), ('-', 'Negative')], default=' ', max_length=10, null=True),
        ),
    ]
