# Generated by Django 4.2.7 on 2024-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_alter_competition_wind_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='wind_direction',
        ),
        migrations.AddField(
            model_name='competition',
            name='result_is_timing',
            field=models.BooleanField(default=True),
        ),
    ]
