# Generated by Django 4.2.7 on 2024-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_remove_competition_wind_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='competition_category',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='competition_position',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='competition_result_timing',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='is_final',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='is_heat',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='is_semi_final',
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_period',
            field=models.CharField(choices=[('Indoor', 'Pista Coberta'), ('Outdoor', 'Ar Livre')], default='Outdoor', max_length=10),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_result',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_wind',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
