# Generated by Django 4.2.7 on 2024-02-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_remove_competition_competition_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competition_category',
            field=models.CharField(choices=[('OW', 'OW 1'), ('DF', 'DF'), ('GW', 'GW'), ('GL', 'GL'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='F', max_length=10),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_result_timing',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='is_heat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='is_semi_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
