# Generated by Django 4.2.7 on 2024-02-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_competition_competition_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='is_final',
            new_name='is_championship',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='competition_category',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='competition_position',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='competition_result',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='is_heat',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='is_semi_final',
        ),
    ]
