# Generated by Django 4.2.7 on 2024-02-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_rename_is_final_competition_is_championship_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='competition_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='competition_local',
            new_name='local',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='competition_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='competition_result_timing',
            new_name='result',
        ),
    ]
