# Generated by Django 4.2.2 on 2023-08-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_rename_athletics_event_group_athlete_event_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='url_fpacompeticoes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
