# Generated by Django 4.2.4 on 2023-09-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_rename_staff_staff_profile'),
        ('athletes', '0004_delete_athleticsevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='main_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_coach_profile', to='staffs.staff'),
        ),
    ]
