# Generated by Django 4.2.2 on 2023-08-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='wind_direction',
            field=models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], default=' ', max_length=10),
        ),
    ]
