# Generated by Django 4.2.2 on 2023-08-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_competitionevent_alter_competition_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='event',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
