# Generated by Django 4.2.2 on 2023-08-27 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0004_delete_athleticsevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('exercise', models.CharField(choices=[('Full Squat', 'Full Squat'), ('Full Front Squat', 'Full Front Squat'), ('1/2 Squat', '1/2 Squat'), ('1/4 Squat', '1/4 Squat'), ('Squat Jump', 'Squat Jump'), ('Bulgarian Squat', 'Bulgarian Squat'), ('Power Clean', 'Power Clean'), ('Hang Clean', 'Hang Clean'), ('Power Snatch', 'Power Snatch'), ('Hang Snatch', 'Hang Snatch'), ('Dead Lift', 'Dead Lift'), ('Bench Press', 'Bench Press'), ('Hip Trust', 'Hip Trust'), ('Lunges', 'Lunges'), ('Chin Up', 'Chin Up'), ('Pull Up', 'Pull Up')], default='Full Squat', max_length=60)),
                ('date', models.DateTimeField()),
                ('exercise_notes', models.CharField(choices=[('Excentric', 'Excentric'), ('Concentric', 'Concentric'), ('Isometric', 'Isometric')], default='Concentric', max_length=60)),
                ('set', models.IntegerField()),
                ('nr_repetitions', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('median_speed', models.IntegerField()),
                ('median_rom', models.IntegerField()),
                ('best_rep', models.JSONField()),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strength_trainings', to='athletes.athlete')),
            ],
        ),
    ]
