# Generated by Django 4.2.2 on 2023-08-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_strengthtraining_left_in_tank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strengthtraining',
            name='best_rep',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
