# Generated by Django 4.2.2 on 2023-08-27 18:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_delete_athleticsevent'),
        ('training', '0003_alter_strengthtraining_best_rep'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumpsTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('jumps_training_type', models.CharField(choices=[('Multijumps', 'Multijumps'), ('Technical Training', 'Technical Training')], default='Multijumps', max_length=60)),
                ('technical_training', models.CharField(choices=[('High Jump', 'High Jump'), ('Long Jump', 'Long Jump'), ('Triple Jump', 'Triple Jump'), ('Pole Vault', 'Pole Vault')], default='Long Jump', max_length=60)),
                ('multijumps_training', models.CharField(choices=[('Horizontal Impulsion', 'Horizontal Impulsion'), ('Triple Step', 'Triple Step'), ('Triple Hop', 'Triple Hop'), ('Penta Step', 'Penta Step'), ('Penta Hop', 'Penta Hop'), ('Deca Step', 'Deca Step'), ('Penta 4 steps', 'Penta 4 steps'), ('Penta 6 steps', 'Penta 6 steps')], default='Penta Step', max_length=60)),
                ('poles_info', models.JSONField(blank=True, null=True)),
                ('nr_steps', models.IntegerField()),
                ('result', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumps_trainings', to='athletes.athlete')),
            ],
        ),
    ]
