# Generated by Django 4.2.2 on 2023-08-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_jumpstraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumpstraining',
            name='height_jump_technique',
            field=models.CharField(choices=[('Tesouras', 'Tesouras'), ('Costas', 'Costas')], default='', max_length=60),
        ),
    ]
