# Generated by Django 4.2.2 on 2023-08-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_jumpstraining_height_jump_technique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jumpstraining',
            old_name='height_jump_technique',
            new_name='high_jump_technique',
        ),
    ]
